# CircleCI automatically reads this file from our repo and uses it for
# configuration. Docs:
# https://circleci.com/docs/2.0/configuration-reference/
# https://circleci.com/docs/2.0/sample-config/
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            pip -V
            pip install . coverage coveralls

      - run:
          name: Run tests
          command: |
            python3 -m coverage run --include=flask_gae_static.py -m unittest discover -v
            python3 -m coverage html -d /tmp/coverage_html
            if [ "$COVERALLS_REPO_TOKEN" != "" ]; then python3 -m coveralls || true; fi

      - store_artifacts:
          path: /tmp/coverage_html
